# Numerical Python or Numpy

<img src="img/numpy.jpg">

## Install Numpy

In [1]:
!pip install numpy

# Import Numpy

In [3]:
import numpy as np

# Numpy Array
<img src="img/np_array.png">
Numpy Array, Type

In [10]:
a = np.array([1,2,3,4,5,6])
print(a)
print(type(a))
b= [1,23,4,5,6]
print(b)
print(type(b))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
[1, 23, 4, 5, 6]
<class 'list'>


# Array Shape, Reshape and Lenght

In [16]:
print(a.shape)
a = a.reshape((2,3))
print(a.shape)

(6,)
(2, 3)


In [26]:
b = np.array(range(0,20)).reshape((2,2,5))
print(b.shape)
c = b.reshape(20)
print(c.shape)

(2, 2, 5)
(20,)


In [34]:
b.shape[2]

5

# Max, Min, ArgMax, ArgMin

In [53]:
a = np.array([[1,2,3],
             [4,5,6],
             [7,80,9]])
print(a.shape)
print(np.max(a))
print(np.argmax(a))
print(np.argmin(a))
print(np.argmax(a, axis=1))

(3, 3)
80
7
0
[2 2 1]


# Zeros, Ones, linspace, Random

In [65]:
n= 2
a = np.zeros((n,2,1))
print(a)
b = np.ones((n,n))
print(b)

[[[0.]
  [0.]]

 [[0.]
  [0.]]]
[[1. 1.]
 [1. 1.]]


In [74]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [91]:
a = np.random.randint(0,10,5)
print(a)
np.random.uniform(0,10,2)

[3 0 4 4 9]


array([2.01076053, 3.05036507])

In [102]:
l = np.random.uniform(0,1000,100)
n = np.array(l)
n = n.reshape((n.shape[0],1))
print(n.shape)
np.max(n)
# np.array([[1],[2],[3]]).shape

(100, 1)


981.7169590955509

# Array Select with Index

In [112]:
a = np.array(range(0,20)).reshape(5,4)
print(a.shape)
print(a)
a[0:2,2:3]

(5, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


array([[2],
       [6]])

# Loop in Array

In [125]:
for i in a[0:2]:
    for j in i[2:3]:
        print(j)

IndexError: invalid index to scalar variable.

# append

In [126]:
a = np.array([1,2,3])
b = np.array([10,20,30])
np.append(a,b)

array([ 1,  2,  3, 10, 20, 30])