In [17]:
import numpy as np
class PreProcessing(object):
    def __init__(self, path):
        self.path = path
    
    def load_data(self):
        self.data = []
        with open(self.path) as csv_file:
            for line in csv_file.readlines():
                line = line.replace('\n','')
                line = line.split(",")
                self.data.append(line)
            dataset = np.array(self.data, np.float32)
            normalized_dataset = (dataset - np.min(dataset)) / (np.max(dataset) - np.min(dataset))
            print(normalized_dataset)
aggregate = PreProcessing("a.csv")
aggregate.load_data()

[[0.         0.14285715 0.2857143  0.42857143]
 [0.5714286  0.71428573 0.85714287 1.        ]
 [0.         0.14285715 0.2857143  0.42857143]
 [0.5714286  0.71428573 0.85714287 1.        ]
 [0.         0.14285715 0.2857143  0.42857143]
 [0.5714286  0.71428573 0.85714287 1.        ]
 [0.         0.14285715 0.2857143  0.42857143]
 [0.5714286  0.71428573 0.85714287 1.        ]
 [0.         0.14285715 0.2857143  0.42857143]
 [0.5714286  0.71428573 0.85714287 1.        ]
 [0.         0.14285715 0.2857143  0.42857143]
 [0.5714286  0.71428573 0.85714287 1.        ]
 [0.         0.14285715 0.2857143  0.42857143]
 [0.5714286  0.71428573 0.85714287 1.        ]
 [0.         0.14285715 0.2857143  0.42857143]
 [0.5714286  0.71428573 0.85714287 1.        ]
 [0.         0.14285715 0.2857143  0.42857143]
 [0.5714286  0.71428573 0.85714287 1.        ]
 [0.         0.14285715 0.2857143  0.42857143]
 [0.5714286  0.71428573 0.85714287 1.        ]
 [0.5714286  0.71428573 0.85714287 1.        ]]


In [ ]:
normalized_dataset = (dataset - np.min(dataset)) / (np.max(dataset) - np.min(dataset))
            print(normalized_dataset)