In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [3]:
a = torch.empty(2)
print(a)
a = torch.empty(2,2)
print(a)

tensor([7.7767e+31, 7.1536e+22])
tensor([[-1.1059e-18,  3.0695e-41],
        [-1.1844e-18,  3.0695e-41]])


In [4]:
a.dtype

torch.float32

In [5]:
torch.rand(2, dtype=torch.float16)

tensor([0.1108, 0.8672], dtype=torch.float16)

In [6]:
torch.ones(2)

tensor([1., 1.])

In [7]:
torch.tensor([2,0.3,0.5])

tensor([2.0000, 0.3000, 0.5000])

In [8]:
a = torch.rand(2)
b = torch.rand(2)
print(a)
print(b)

tensor([0.2632, 0.6256])
tensor([0.3372, 0.1143])


In [9]:
print(a + b)
print(torch.add(a,b))
a.add_(b)
print(a)

tensor([0.6004, 0.7399])
tensor([0.6004, 0.7399])
tensor([0.6004, 0.7399])


+, add, add_
*, mul, mul_
/, div, div_

sliceing

In [10]:
a = torch.rand(5,3)
print(a)
print(a[:,0])

tensor([[0.1737, 0.0302, 0.8177],
        [0.2874, 0.0335, 0.4549],
        [0.1482, 0.4464, 0.6344],
        [0.3455, 0.0816, 0.5798],
        [0.2838, 0.0525, 0.3706]])
tensor([0.1737, 0.2874, 0.1482, 0.3455, 0.2838])


In [11]:
a[1,1].item()

0.033455848693847656

In [14]:
a = torch.rand(2,2)
print(a)
b = a.view(4) # Reshape
print(b)
print(a.view(-1))# don't set shape
print(a.resize(4)) # Reshape
print(a.size()) # a.shape

tensor([[0.7701, 0.1068],
        [0.6957, 0.6218]])
tensor([0.7701, 0.1068, 0.6957, 0.6218])
tensor([0.7701, 0.1068, 0.6957, 0.6218])
tensor([0.7701, 0.1068, 0.6957, 0.6218])
torch.Size([2, 2])


Tensor to Numpy Array

In [15]:
import numpy as np
a = torch.ones(5)
print(a)
b = a.numpy() # a and b have one memory location
print(type(b))
print(b)
a.add_(1) # inplace add
print("inplace added")
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>
[1. 1. 1. 1. 1.]
inplace added
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Numpy Array to Tensor (Inplace)

In [16]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)
a+=1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


GPU

In [17]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
    z = z.to("cpu")


In [18]:
x = torch.ones(5, requires_grad=True) # default is false, if is true => need calcalet gradeant in optimization process
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
