In [9]:
import torch
import torch.nn as nn
import numpy as np

In [10]:
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=0)

In [11]:
x = np.array([2.0, 1.0, 0.1])
softmax(x)

array([0.65900114, 0.24243297, 0.09856589])

In [15]:
torch.softmax(torch.tensor([2.0, 1.0, 0.1]), dim=0)

tensor([0.6590, 0.2424, 0.0986])

# Cross Entropy

In [19]:
def cross_entropy(actual, predicted):
    loss = - np.sum(actual * np.log(predicted))
    return loss


Y = np.array([1, 0, 0])
Y_pred_good = np.array([0.7, 0.2, 0.1])
Y_pred_bad = np.array([0.1, 0.3, 0.6])

print("Good Loss:", cross_entropy(Y, Y_pred_good))
print("Bas Loss:", cross_entropy(Y, Y_pred_bad))

Good Loss: 0.35667494393873245
Bas Loss: 2.3025850929940455


In [25]:
loss = nn.CrossEntropyLoss()

Y = torch.tensor([2, 0, 1])
######################
# Y is not OneHot format and Y_pred is raw Scores(logits), no Softmax
######################
Y_pred_good = torch.tensor([[0.1, 1.0, 2.1], [2.0, 1.0, 0.1], [0.1, 3.0, 0.1]])
Y_pred_bad = torch.tensor([[2.1, 1.0, 0.1], [0.1, 1.0, 2.1], [0.1, 3.0, 0.1]])

print("Good Loss:", loss(Y_pred_good, Y))
print("Bas Loss:", loss(Y_pred_bad, Y))

_, pred1 = torch.max(Y_pred_good, 1)
_, pred2 = torch.max(Y_pred_bad, 1)
print(pred1, pred2)

Good Loss: tensor(0.3018)
Bas Loss: tensor(1.6242)
tensor([2, 0, 1]) tensor([0, 2, 1])
